name: Deploy to Docker Hub

on:
  push:
    paths:
      - apps/discord-bot
    branches:
      - master
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: gdschongikoc/discord-bot
          registry: docker.io
          directory: apps/discord-bot
          dockerfile: apps/discord-bot/Dockerfile.prod
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
