name: Deploy Discord Bot Image to Docker Hub

on:
  push:
    paths:
      - apps/discord-bot
      - .github/workflows/discord-deploy.yml
    branches:
      - master
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        working-directory: apps/discord-bot
        run: docker build -f Dockerfile.prod -t ${{ secrets.DOCKERHUB_USERNAME }}/discord-bot:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/discord-bot:latest
